name: Buildscientist
description: A systems/software engineer that loves science and building things.
meta_description: "buildscientist,software engineering,devops"

aboutPage: true

markdown: kramdown
highlighter: rouge
timezone: America/Vancouver
encoding: utf-8
paginate: 20
baseurl: /
domain_name: 'http://buildscientist.com'
google_analytics: 'UA-63689884-1'
disqus: false
disqus_shortname: 'your-disqus-shortname'

gems: [jekyll-paginate,jekyll-gist,jekyll-watch]

kramdown:
  input: GFM

# Details for the RSS feed generator
url:            'http://buildscientist.com'
author:         'Youssuf ElKalay'
authorTwitter:  'buildscientist'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
